version: 2
jobs:
  build:
    working_directory: /buildslave/extract
    docker:
      - image: alexcrichton/rust-slave-dist:2017-02-02
        environment:
          CARGO: ~/.cargo/bin/cargo
    steps:
      - checkout
      - restore_cache:
          keys: 
            - extract-rust-deps-{{ checksum Cargo.lock }}
      - run: 
          name: Install Rust
          command: 
            curl https://sh.rustup.rs -sSf | sh -s -- -y -v;
            . ~/.profile;
            env
      - run:
          name: build
          command: 
            . ~/.profile;
            cargo build -v
      - save_cache:
          key: extract-rust-deps-{{ checksum Cargo.lock }}
          paths:
            - ~/.cargo/registry
            - /buildslave/extract/target
      - run:
          name: test
          command: 
            . ~/.profile;
            cargo test
