version: 2
jobs:
  build:
    working_directory: /buildslave/extract
    docker:
      - image: alexcrichton/rust-slave-dist:2017-02-02
        environment:
          CARGO: ~/.cargo/bin/cargo
    steps:
      - checkout
      - run: 
          name: Install Rust
          command: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - run:
          name: build
          command: $CARGO build -v
      - run:
          name: test
          command: $CARGO test
